---
title: 'STA 141A Spring 2020: Homework 1'
author: 'Instructor: Vaidotas Characiejus'
date: "4/5/2020"
output:
  html_document:
    number_sections: yes
---



The assignment has to be done in an [R Markdown](https://rmarkdown.rstudio.com) document. The assignment has to be submitted electronically on Canvas until the deadline of April 15, 2020 at 6:00 PM by uploading two files:

1. an HTML or PDF file;
2. the Rmd source file.

It is possible to upload two files on Canvas. Late submissions will not be accepted.

Each answer has to be based on `R` code that shows how the result was obtained. `R` code has to answer the question or solve the task. For example, if you are asked to find the largest entry of a vector, `R` code has to return the largest element of the vector. If `R` code just prints all values of the vector and you determine by hand which element is the largest, this will not be accepted as an answer. No points will be given for answers that are not based on `R` code. 

There are many possible ways to write `R` code that is needed to answer the questions or do the tasks, but for some of the questions or tasks you might have to use something that has not been discussed during the lectures or the discussion sessions. You will have to come up with a solution on your own. This is a very important part of learning (if not the most important part of learning). Try to understand what you need to do to complete the task or answer the question and feel free to search the Internet for possible solutions and discuss possible solutions with other students. It is perfectly fine to ask what kind of an approach or a function other students use. However, you are not allowed to share your code or your answers with other students. Everyone has to write the code, do the tasks and answer the questions on their own. To put it simply, collaborate but do not plagiarize.

The total number of points of this assignment is 30.

Good luck!

# Vectors and simulation
Suppose that we have:

+ four types of animals: `cat`, `dog`, `cow`, `squirrel`;
+ four possible colors: `white`, `black`, `brown`, `red`;
+ five possible attributes: `big`, `small`, `angry`, `cute`, `finicky`.

a. Generate random samples with replacement of size `100` from each of the types. Call the resulting vectors of character strings as: `Animal`, `Color`, `Attribute` (1 point). 
b. Compute how many animals in the sample are cats or dogs (1 point).
c. Write `R` code to combine the results to produce phrases (character strings) describing the animals as in this example: `big white dog` (2 points).
d. Create a contingency table between `Animal` and `Attribute` (1 point).



# Matrices
Consider the following system of linear equations
\begin{align*}
x_1+2x_2+3x_3+4x_4+5x_5&=7,\\
2x_1+x_2+2x_3+3x_4+4x_5&=-1,\\
3x_1+2x_2+x_3+2x_4+3x_5&=-3,\\
4x_1+3x_2+2x_3+x_4+2x_5&=5,\\
5x_1+4x_2+3x_3+2x_4+x_5&=17.
\end{align*}

a. Create the matrix `A` and the vector `y` corresponding to the matrix equation $Ax=y$, where $A\in\mathbb R^{5\times 5}$ and $x,y\in\mathbb R^5$ (1 point).
b. Determine if the matrix `A` is invertible (2 points).
c. Find the solution of the system of linear equations (2 points).
d. Verify that your solution is correct (1 point).



# Data exploration
The task is to explore the US census population estimates by county for 2015 from the package `usmap` (load the data frame from `countypop.RData`). The data frame has `3142` rows and `4` variables: `fips` is the 5-digit FIPS code corresponding to the county; `abbr` is the 2-letter state abbreviation; `county` is the full county name; `pop_2015` is the 2015 population estimate (in number of people) for the corresponding county. Each row of the data frame represents a different county or a county equivalent. For the sake of simplicity, when we say a county, that also includes a county equivalent and when we say a state, that also includes the District of Columbia. Answer the following questions.

a. How many unique 2-letter state abbreviations are there (1 point)?
b. What is the total number of counties in the US (1 point)?
c. How many unique county names are there (1 point)?
d. What are the top 10 most common county names (2 points)?
e. Which state has the largest number of counties? Which state has the smallest number of counties (1 points)?
f. What is the average population of a county in the US (1 point)?
g. Which state has the largest county in terms of population? How many people live in the largest county in terms of population (2 points)?
h. What is the largest county in terms of population of each of the states (2 points)?
i. What is the average population of the 100 largest counties in the US (2 points)?
j. How many people live in each of the states (2 points)?
k. What is the average population of a county in California (2 points)?
l. What is the average population of a county in each of the states (2 points)?